Form
Mitrovic-Milan/capstone-project-enhanced pull request #3
Opened 2022-07-27 14:36 UTC by Mitrovic-Milan

Ich habe mehrere kommponents erstellt (Header, listen Element und das form element). 
Die Seite ist dynamisch und funktionsfehig. Der Submit Button ist in Storybook erstelt. Sowie Styled components.

2022-07-27 15:10 UTC, stefankorder requested changes
Good work! Please take a look at my comments. If there are questions feel free to contact me.

2022-07-27 15:10 UTC, stefankorder commented on src/App.js
> +};
Don't wrap divs within divs. Div tags should only be used for styling.

2022-07-27 15:10 UTC, stefankorder commented on src/components/Button.js
> +};
You don't need a component that just wraps a button tag. You can use the button tag directly instead of the component.

2022-07-27 15:10 UTC, stefankorder commented on src/App.js
> +        <Styleddiv>
StyledDiv is not a good name. You'd better think about which element to show it. For example, your div shows a card, so the name could be StyledCard.

2022-07-27 15:10 UTC, stefankorder commented on src/App.js
> +        <Styleddiv2>
StyledDiv2 is not a good name. You'd better think about which element to show it. For example, your div shows a card, so the name could be StyledCard.

2022-07-29 11:58 UTC, tomsmulski commented
everything looks good, keep up the good work

2022-07-29 12:06 UTC, merged

2022-07-29 13:27 UTC, JessicaLoers reviewed
**Hi @Mitrovic-Milan**  ✌️
It's a pity that you have already merged this branch because there is a very important topic that you should keep in mind - **pass props down, lift state up!**  

Please look at my comments 🙂

2022-07-29 13:27 UTC, JessicaLoers commented on src/App.js
>        </div>
there is no need to wrap the `<Header />` component in a `<div>` element  - please remove 🙂

2022-07-29 13:27 UTC, JessicaLoers commented on src/App.js
> +        <TodosList todos={todos} setTodos={setTodos} />
Please remove `setTodos={setTodos}`, firstly you don't use it at all in ` <TodosList />` and secondly it is not a good practice to pass setter functions to components and could cause problems in the future.

2022-07-29 13:27 UTC, JessicaLoers commented on src/App.js
> +        <Form input={input} setInput={setInput} todos={todos} setTodos={setTodos} />
Like I mentioned in my comment above, please don't pass setter functions to components. 

The solution is to wrap your state updater function (setter function) in a callback function and pass that into your child - it's called state up lifting.  
In [THIS ARTICLE](https://www.robinwieruch.de/react-lift-state/) you can read more about this topic. Please note that the syntax is slightly different.

2022-07-29 13:27 UTC, JessicaLoers commented on src/components/TodosList.js
>          <li className="list-item" key={todo.id}>
What do you need this css class for? 🧐

2022-07-29 13:27 UTC, JessicaLoers commented on src/components/TodosList.js
>            <span className="list">{todo.title}</span>
What do you need this css class for? 🧐

2022-07-29 13:27 UTC, JessicaLoers commented on src/App.js
>      <div className="container">
What do you need this css class for? 🧐