newdelet icon
Mitrovic-Milan/capstone-project-enhanced pull request #4
Opened 2022-08-01 14:27 UTC by Mitrovic-Milan

2022-08-02 08:49 UTC, stefankorder requested changes
Good work! Please take a look at my comments. If you need any help with the implementation please contact me.

2022-08-02 08:49 UTC, stefankorder commented on src/components/Button.js
> +      {textValue === 'Delete' ? <Icon icon="ant-design:delete-outlined" style={{fontsize: '28px'}} /> : ''}
You do not need two different tenery's for this case. You can solve this with one single tenery.

2022-08-02 08:49 UTC, stefankorder commented on src/components/Form.js
> +    newInput('');
The whole logic should be at the level your state is managed. Keep your components stupid as possible.

2022-08-02 08:49 UTC, stefankorder commented on src/components/Form.js
> +    newInput(e.target.value);
The whole logic should be at the level your state is managed. Keep your components stupid as possible.

2022-08-02 08:49 UTC, stefankorder commented on src/components/TodosList.js
> +    deleteTodo(todoid);
The whole logic should be at the level your state is managed. Keep your components stupid as possible.

2022-08-10 14:13 UTC, actyralf requested changes

2022-08-10 14:13 UTC, actyralf commented on src/util/LocalStorage.js
> +  return JSON.parse(value);
`JSON.parse()` can fail and throw an error when called with invalid JSON data. You need to handle this situation with a `try/catch` block.

2022-08-16 09:57 UTC, merged